import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import ClerkThemeProvider from "@/components/ClerkThemeProveder";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
    <ClerkThemeProvider>
    <html lang="en">
      <body
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
    </ClerkThemeProvider>
    </ThemeProvider>
  );
}
